ruby: rubocop-factory_bot gem に対応
timedia/styleguide pull request #107
Opened 2023-05-23 10:42 UTC by tk0miya

rubocop-rspec-2.22.0 から factory_bot 関連の機能が別の gem
(rubocop-factory_bot gem) に切り出されることになったため、
依存関係に rubocop-factory_bot gem を追加した。

また、今後設定を増やすことを想定し、factory_bot 用の空の YAML ファイルを
用意した。

https://github.com/rubocop/rubocop-rspec/blob/master/CHANGELOG.md#2220-2023-05-06

2023-05-23 23:46 UTC, epaew commented on ruby/Gemfile
メインの用途は CI ですかね。  
「`config/` 以下のYAML のインデントが狂ってて Cop の読み込みに失敗する」とか、そんなくだらないレベルのものは流石に検出したいなと動かしてる workflow があります
https://github.com/timedia/styleguide/blob/master/.github/workflows/ruby.yaml

この Gemfile は
- RuboCop を実行するための依存関係の定義であり、
- RuboCop での Lint 対象

ですね

2023-05-23 23:46 UTC, epaew commented on ruby/Gemfile
> +gem 'rubocop-rspec', '~> 2.22.0'
メモ：

「`rubocop-factory_bot` の追加」だけじゃなくて「`rubocop-rspec` の最低要求バージョン変更」も同時にしてるのは、  
このバージョンから gem が分割されたから = 古い `rubocop-rspec` だと `RSpec/FactoryBot/*` Cop が存在するから

2023-05-23 23:46 UTC, epaew commented on ruby/Gemfile
> +gem 'rubocop', '~> 1.47.0'
`rubocop-rspec` の最低要求バージョンが同時に変更されてるのは別でコメントしたとおりで問題ないと思っていますが、

- なぜこの行の「`rubocop` の最低要求バージョン」を変えたのか
- なぜ `rubocop-config-timedia.gemspec` 側の「`rubocop` の最低要求バージョン」はそのままなのか

は、わかりませんでした。

↓このあたりを見るかぎりは、「1.33以上」のままで良さそうなのですが。
- https://github.com/rubocop/rubocop-rspec/blob/cd6a30efa9094e389cf9e4dd473b7631fe18bab1/rubocop-rspec.gemspec#L40
- https://github.com/rubocop/rubocop-factory_bot/blob/3324d183912e4ef740b55fad31ba15d40f6b75b6/rubocop-factory_bot.gemspec#L36

2023-05-23 23:51 UTC, epaew requested changes

2023-05-23 23:51 UTC, epaew commented on ruby/Gemfile
> そんなくだらないレベルのものは流石に検出したい

そういう意味だと、今回追加してもらった `factory_bot.yml` を↓にも追加してもらわないといけないですね。
https://github.com/timedia/styleguide/blob/master/ruby/.rubocop.yml

2023-05-23 23:56 UTC, epaew commented on ruby/rubocop/config/factory_bot.yml
https://github.com/timedia/styleguide/tree/master/ruby/rubocop/config

`config/` 以下の各YAMLファイルと並べてみて思ったのですが、  
↓程度の内容は現時点で書いてあっても良いのではないでしょうか？

```yaml
# RuboCop FactoryBot の設定ファイル
# 通常、基本設定ファイル (base.yml) と同時に利用する

require: rubocop-factory_bot

########################################
# FactoryBot Cops: TODO
########################################
```

2023-05-25 01:38 UTC, epaew commented on ruby/Gemfile
> +gem 'rubocop', '~> 1.47.0'
@tk0miya 他は後からや別PRでもいいんですけど、ここは理由が知りたいです

2023-05-29 11:26 UTC, tk0miya commented on ruby/Gemfile
> +gem 'rubocop', '~> 1.47.0'
rubocop-rspec が依存する rubocop-capybara が以下のような依存関係になっているため、 CI が失敗していたのでアップデートしています。
https://github.com/rubocop/rubocop-capybara/blob/main/rubocop-capybara.gemspec#L35
https://github.com/timedia/styleguide/actions/runs/5056301241/jobs/9073592828

ただ、エラーメッセージにも gemspec にも 1.41 以上とでているのに、なぜか 1.47.0 にしていてなぜこうしたのかは記憶が定かではないです。
1.41.0 に下げたほうが良さそうな気がします。

2023-05-29 11:33 UTC, tk0miya commented on ruby/Gemfile
> +gem 'rubocop', '~> 1.47.0'
下げました。

2023-05-29 11:34 UTC, tk0miya commented on ruby/rubocop/config/factory_bot.yml
done

2023-05-29 11:34 UTC, tk0miya commented on ruby/Gemfile
done

2023-05-29 11:57 UTC, epaew commented on ruby/Gemfile
> +gem 'rubocop', '~> 1.47.0'
なるほど。 `rubocop-capybara` の依存関係までは見てませんでしたね。。了解です

2023-05-31 01:18 UTC, merged